# Generated by Django 6.0.3 on 2026-03-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userotp_email_alter_userotp_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['order'], 'verbose_name': 'عنوان', 'verbose_name_plural': 'العناوين'},
        ),
        migrations.AlterModelOptions(
            name='userotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'رمز تحقق OTP', 'verbose_name_plural': 'رموز التحقق'},
        ),
    ]
