# Generated by Django 6.0.3 on 2026-03-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_variant_details'),
        ('orders', '0002_order_guest_email_order_shipping_city_and_more'),
    ]

    operations = [
    ]
