# Generated by Django 6.0.3 on 2026-03-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20260329_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سلة تسوق', 'verbose_name_plural': 'سلات التسوق'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'عنصر سلة', 'verbose_name_plural': 'عناصر السلات'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر طلب', 'verbose_name_plural': 'عناصر الطلبات'},
        ),
    ]
