# Generated by Django 6.0.3 on 2026-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('whatsapp', 'واتساب'), ('call', 'مكالمة هاتفية')], default='whatsapp', max_length=20, verbose_name='طريقة التواصل المفضلة'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, help_text='أي ملاحظات إضافية للطلب', null=True, verbose_name='ملاحظات الطلب'),
        ),
    ]
