# Generated by Django 6.0.3 on 2026-04-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('icon', models.CharField(default='📁', help_text='أيقونة Emoji أو نص قصير', max_length=50)),
                ('is_hot', models.BooleanField(default=False, help_text='هل هذا القسم من الأقسام المشهورة؟')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order'],
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'لون',
                'verbose_name_plural': 'الألوان',
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='السعر القديم (للخصم)', max_digits=10, null=True)),
                ('is_new', models.BooleanField(default=True, help_text='هل المنتج جديد؟')),
                ('is_hot', models.BooleanField(default=False, help_text='هل المنتج مشهور/مبيع؟')),
                ('is_active', models.BooleanField(default=True, help_text='هل المنتج متاح؟')),
                ('has_patterns', models.BooleanField(default=False, help_text='هل المنتج يحتوي على أنماط؟')),
                ('has_product_level_sizes', models.BooleanField(default=False, help_text='هل المنتج يحتوي على مقاسات على مستوى المنتج؟')),
                ('has_colors', models.BooleanField(default=False, help_text='هل المنتج يحتوي على ألوان فقط؟ (بدون أنماط أو مقاسات)')),
                ('rating', models.FloatField(default=5.0, help_text='التقييم من 0 إلى 5')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['order'],
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='products.product')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('has_sizes', models.BooleanField(default=False, help_text='هل هذا النمط يتطلب اختيار مقاس؟')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='السعر الأساسي للنمط (إذا لم يكن له مقاسات)', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'نمط',
                'verbose_name_plural': 'الأنماط',
                'ordering': ['order'],
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='products.product')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'لون منتج',
                'verbose_name_plural': 'ألوان المنتجات',
                'ordering': ['order'],
                'unique_together': {('product', 'color')},
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
                ('order', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, help_text='السعر لهذا المقاس على مستوى المنتج', max_digits=10)),
            ],
            options={
                'verbose_name': 'مقاس منتج',
                'verbose_name_plural': 'مقاسات المنتجات',
                'ordering': ['order'],
                'unique_together': {('product', 'size')},
                'indexes': [models.Index(fields=['product', 'size'], name='products_pr_product_0d657d_idx')],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='PatternSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_sizes', to='products.pattern')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
                ('price', models.DecimalField(decimal_places=2, help_text='السعر لهذا المقاس في هذا النمط', max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='المخزون المتاح لهذا المقاس في هذا النمط')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'مقاس نمط',
                'verbose_name_plural': 'مقاسات الأنماط',
                'ordering': ['order'],
                'unique_together': {('pattern', 'size')},
                'indexes': [models.Index(fields=['pattern', 'size'], name='products_pa_pattern_23e715_idx'), models.Index(fields=['pattern', 'stock'], name='products_pa_pattern_7be371_idx')],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='PatternColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_colors', to='products.pattern')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_colors', to='products.color')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'لون النمط',
                'verbose_name_plural': 'ألوان الأنماط',
                'ordering': ['order'],
                'unique_together': {('pattern', 'color')},
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='PatternImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_images', to='products.pattern')),
                ('color', models.ForeignKey(blank=True, help_text='اختياري: اربط الصورة بلون معين لعرضها عند اختياره', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_images', to='products.color')),
                ('image', models.ImageField(upload_to='patterns/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'صورة النمط',
                'verbose_name_plural': 'صور الأنماط',
                'ordering': ['order'],
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['order'],
                'indexes': [],
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.pattern')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size')),
                ('order', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, help_text='DEPRECATED: Use Product.get_price() instead', max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'متغير منتج',
                'verbose_name_plural': 'متغيرات المنتجات',
                'ordering': ['order'],
                'unique_together': {('product', 'pattern', 'color', 'size')},
                'indexes': [models.Index(fields=['product', 'pattern', 'size'], name='products_pr_product_63d118_idx'), models.Index(fields=['product', 'stock'], name='products_pr_product_82d8bd_idx'), models.Index(fields=['product', 'pattern', 'color', 'size'], name='products_pr_product_715942_idx')],
                'constraints': [],
            },
        ),
    ]
