# Generated by Django 6.0.3 on 2026-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_multilevel_pricing'),
        ('products', '0007_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
    ]
