# Generated by Django 6.0.3 on 2026-03-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20260329_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'لون', 'verbose_name_plural': 'الألوان'},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'ordering': ['order'], 'verbose_name': 'نمط', 'verbose_name_plural': 'الأنماط'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['order'], 'verbose_name': 'لون منتج', 'verbose_name_plural': 'ألوان المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'صورة منتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['order'], 'verbose_name': 'مقاس منتج', 'verbose_name_plural': 'مقاسات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['order'], 'verbose_name': 'مواصفة', 'verbose_name_plural': 'مواصفات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['order'], 'verbose_name': 'متغير منتج', 'verbose_name_plural': 'متغيرات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'مقاس', 'verbose_name_plural': 'المقاسات'},
        ),
        migrations.RenameIndex(
            model_name='patternsize',
            new_name='products_pa_pattern_23e715_idx',
            old_name='products_pa_pattern_idx',
        ),
        migrations.RenameIndex(
            model_name='patternsize',
            new_name='products_pa_pattern_7be371_idx',
            old_name='products_pa_pattern_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='productsize',
            new_name='products_pr_product_0d657d_idx',
            old_name='products_pr_product_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_63d118_idx',
            old_name='products_pr_product_pattern_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_82d8bd_idx',
            old_name='products_pr_product_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_715942_idx',
            old_name='products_pr_product_full_idx',
        ),
    ]
