# Generated by Django 6.0.3 on 2026-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_colors',
            field=models.BooleanField(default=False, help_text='هل المنتج يحتوي على ألوان فقط؟ (بدون أنماط أو مقاسات)'),
        ),
    ]
