# Generated by Django 6.0.3 on 2026-04-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_normalize_home_collection_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'مواصفة',
                'verbose_name_plural': 'مواصفات المنتجات',
                'ordering': ['order'],
            },
        ),
        migrations.RenameIndex(
            model_name='homeproductcollectionitem',
            new_name='products_ho_collect_bf8f80_idx',
            old_name='products_ho_collect_7bc669_idx',
        ),
        migrations.RenameIndex(
            model_name='producttype',
            new_name='products_pr_product_0d4697_idx',
            old_name='products_pr_product_5bf3c1_idx',
        ),
        migrations.RenameIndex(
            model_name='producttypecolor',
            new_name='products_pr_product_3dbd44_idx',
            old_name='products_pr_product_a92f6a_idx',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='products.product'),
        ),
    ]
