# Generated by Django 6.0.3 on 2026-05-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productspecification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['order'], 'verbose_name': 'مواصفة', 'verbose_name_plural': 'مواصفات المنتجات'},
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='عنوان الشريحة')),
                ('image', models.ImageField(upload_to='home/slides/', verbose_name='صورة السلايدر')),
                ('link_url', models.CharField(blank=True, help_text='يمكن استخدام رابط داخلي مثل /products/ أو رابط كامل يبدأ بـ https://', max_length=500, verbose_name='رابط الشريحة')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='النص البديل للصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شريحة السلايدر',
                'verbose_name_plural': 'شرائح السلايدر',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='products_he_is_acti_88a237_idx')],
            },
        ),
    ]
