# Generated by Django 6.0.3 on 2026-05-14 09:32

from django.db import migrations, models


def seed_default_exclusive_offers(apps, schema_editor):
    offer_model = apps.get_model('products', 'HomeExclusiveOffer')
    defaults = [
        {
            "tag": "المشتركات",
            "title": "أحدث المشتركات\nبأسعار حصرية",
            "discount_text": "حتى 60%",
            "button_label": "تسوق الآن",
            "link_url": "/products/",
            "tone": "dark",
            "order": 0,
            "fallback_static_image": "image/3-336.webp",
        },
        {
            "tag": "الكشاف والإضاءة",
            "title": "أحدث التصاميم\nلإضاءة مثالية",
            "discount_text": "",
            "button_label": "اكتشف الآن",
            "link_url": "/products/",
            "tone": "yellow",
            "order": 1,
            "fallback_static_image": "image/21-2-336.webp",
        },
        {
            "tag": "دواية ديكور",
            "title": "ديكورات\nدوايات مميزة",
            "discount_text": "من 100 ج.م",
            "button_label": "تصفح الآن",
            "link_url": "/products/",
            "tone": "light",
            "order": 2,
            "fallback_static_image": "image/15-336.webp",
        },
    ]

    for offer in defaults:
        offer_model.objects.get_or_create(
            tag=offer["tag"],
            title=offer["title"],
            defaults=offer,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeExclusiveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80, verbose_name='وسم العرض')),
                ('title', models.TextField(verbose_name='عنوان العرض')),
                ('discount_text', models.CharField(blank=True, max_length=80, verbose_name='نص الخصم أو السعر')),
                ('button_label', models.CharField(default='تسوق الآن', max_length=80, verbose_name='نص الزر')),
                ('link_url', models.CharField(blank=True, default='/products/', help_text='يمكن استخدام رابط داخلي مثل /products/ أو رابط كامل يبدأ بـ https://', max_length=500, verbose_name='رابط العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/offers/', verbose_name='صورة العرض')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='النص البديل للصورة')),
                ('tone', models.CharField(choices=[('dark', 'داكن'), ('yellow', 'أصفر'), ('light', 'فاتح')], default='dark', max_length=16, verbose_name='نمط البطاقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('fallback_static_image', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عرض حصري في الصفحة الرئيسية',
                'verbose_name_plural': 'العروض الحصرية في الصفحة الرئيسية',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='products_ho_is_acti_d10ba6_idx')],
            },
        ),
        migrations.RunPython(seed_default_exclusive_offers, migrations.RunPython.noop),
    ]
