# Generated by Django 6.0.3 on 2026-05-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_homeexclusiveoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text='هل يظهر المنتج بشارة الأكثر مبيعًا؟', verbose_name='الأكثر مبيعًا'),
        ),
    ]
